animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'

urlpatterns = [
    path('<int:pk>/', views.animal_detail, name='animal_detail'),
    path('<int:pk>/delete', views.animal_delete, name='animal_delete'),
    path('<int:pk>/edit', views.animal_edit, name="animal_edit"),
    path('<int:pk>/image-new', views.animal_image, name="animal_image"),
    #path('owner/<owner_pk>/animal', views.owner_animal_landing, name='owner_animal_landing'),
    path('', views.animal_list, name="animal_list"),
    path('<species>/new', views.new_animal, name='new_animal'),
    path('<species>/<owner_pk>/new', views.new_animal, name='new_animal'),
]

people/urls.py
from django.contrib import admin
from django.urls import path

from people import views

app_name = 'people'

urlpatterns = [
    path('<int:pk>/delete', views.owner_delete, name='owner_delete'),
    path('<int:pk>/edit', views.owner, name='owner_edit'),
    path('<int:pk>/', views.owner_detail, name='owner_detail'),
]

shelter/urls.py
from django.urls import path, include
from shelter import views

app_name = 'shelter'
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register(r'shelter', views.ShelterViewSet)
router.register(r'building', views.BuildingViewSet, basename='building')
router.register(r'room', views.RoomViewSet, basename='room')
# router.register('buildings/shelter/<int:shelter>', views.BuildingFilteredView)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.shelter_landing, name="shelter_landing"),
    path('list', views.shelter_list, name="shelter_list"),
    #Shelter Management URLs
    path('new', views.shelter, name='shelter'),
    path('<int:pk>/edit/', views.shelter, name='shelter'),
    path('<int:pk>/', views.shelter_detail, name='shelter_detail'),
    path('<int:shelter_pk>/building/', views.building, name='building'),
    path('<int:shelter_pk>/building/<int:pk>', views.building, name='building'),
    path('building/<int:pk>/', views.building_detail, name='building_detail'),
    path('building/<int:building_pk>/room', views.room, name='room'),
    path('building/<int:building_pk>/room/<int:pk>', views.room, name='room'),
    path('room/<int:pk>/', views.room_detail, name='room_detail'),
    path('<obj_type>/<int:pk>/delete', views.shelter_object_delete, name='shelter_object_delete'),

    # Animal Placement URLs
    path('<int:animal_pk>/shelter', views.shelter_animal_shelter_select, name='shelter_animal_shelter_select'),
    path('<int:animal_pk>/<int:shelter_pk>/buildings', views.shelter_animal_building_select, name='shelter_animal_building_select'),
    path('<int:animal_pk>/<int:building_pk>/rooms', views.shelter_animal_room_select, name='shelter_animal_room_select')

]

urls.py
import views
import settings
from django.contrib import admin
from django.views.static import serve
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from knox import views as knox_views
from accounts.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('animals/', include('animals.urls')),
    path('evac/', include('evac.urls')),
    path('hotline/', include('hotline.urls')),
    path('intake/', include('intake.urls')),
    path('location/', include('location.urls')),
    path('people/', include('people.urls')),
    path('shelter/', include('shelter.urls')),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})]

animals/models.py
from django.db import models

from animals.choices import ALL_AGE_CHOICES, ALL_SIZE_CHOICES, SEX_CHOICES, SPECIES_CHOICES, STATUS_CHOICES
from animals.colors import ALL_COLOR_CHOICES, ALL_PATTERN_CHOICES
from location.models import Location
from hotline.models import ServiceRequest
from people.models import Person


# Create your models here.
class Animal(Location):

    request = models.ForeignKey(ServiceRequest, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(Person, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(upload_to='images/', null=True)

    #choice fields
    species = models.CharField(max_length=50, choices=SPECIES_CHOICES, blank=True, null=True)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, blank=True, null=True)
    pcolor = models.CharField(max_length=50, choices=ALL_COLOR_CHOICES, verbose_name='Primary Color' , blank=True, null=True)
    scolor = models.CharField(max_length=50, choices=ALL_COLOR_CHOICES, verbose_name='Secondary Color', blank=True, null=True)
    color_notes = models.CharField(max_length=200, blank=True, null=True)
    size = models.CharField(max_length=10, choices=ALL_SIZE_CHOICES, blank=True, null=True)
    age = models.CharField(max_length=10, choices=ALL_COLOR_CHOICES, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, blank=True, null=True, default='REPORTED')

    #boolean fields
    fixed = models.BooleanField(blank=True, null=True)
    aggressive = models.BooleanField(blank=True, null=True)
    confined = models.BooleanField(blank=True, null=True)
    attended_to = models.BooleanField(blank=True, null=True)
    collared = models.BooleanField(blank=True, null=True)

    #text fields
    behavior_notes = models.TextField(blank=True, null=True)
    last_seen = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)

    @property
    def info(self):
        return '%s (%s, %s, %s)' % (self.name.capitalize(), self.species.capitalize(), self.sex)

    @property
    def location_type(self):
        return 'animal'

    class Meta:
        ordering = []

animals/forms.py
from django import forms
from animals.models import Animal
from animals.choices import ANIMAL_LOOKUP_DICT
from location.forms import LocationForm

class AnimalForm(LocationForm):
    behavior_notes = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))  

    def __init__(self, species, owner=None, *args, **kwargs):
        super(AnimalForm, self).__init__(owner, *args, **kwargs)
        self.fields['species'].initial = species
        self.fields['pcolor'].choices = ANIMAL_LOOKUP_DICT[species]['pcolor']
        self.fields['scolor'].choices = ANIMAL_LOOKUP_DICT[species]['scolor']
        self.fields['owner'].initial = owner
        if owner:
            self.set_initial_location(owner)

    class Meta:
        model = Animal
        exclude = ('latitude', 'longitude', 'request', 'image', 'status')
        widgets = {'owner': forms.HiddenInput()}

class ImageForm(forms.ModelForm):

    image = forms.ImageField(required=True)

    class Meta:
        model = Animal
        fields = ['image']

animals/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from people.models import Person
from animals.models import Animal
from animals.forms import AnimalForm, ImageForm


# Create your views here.
def animal_list(request):
    animal_list = Animal.objects.all()
    context = {
    'animal_list':animal_list,
    }
    return render(request, 'animal_list.html', context)

def new_animal(request, species, owner_pk=None):
    owner = Person.objects.get(pk=owner_pk) if owner_pk else None
    form = AnimalForm(species, owner, request.FILES, request.FILES or None, request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse_lazy('animals:animal_list'))
    return render(request, 'animal.html', {'form':form})

def animal_detail(request, pk):
    animal = get_object_or_404(Animal, pk=pk)
    data = {'animal':animal}
    return render(request,'animal_detail.html', data)


def animal_edit(request, pk):
    animal = get_object_or_404(Animal, pk=pk)
    form = AnimalForm(animal.species, animal.owner, request.POST or None, instance=animal)
    if form.is_valid():
        form.save()
        return redirect('animals:animal_detail', pk=pk)
    return render(request, 'animal.html', {'form':form})

def animal_delete(request, pk):
    animal = get_object_or_404(Animal, pk=pk)
    if request.POST:
        animal.delete()
        return render(request, 'animal_delete_success.html')
    data = {'animal':animal}
    return render(request, 'animal_delete.html', data)

def animal_image(request, pk):
    animal = get_object_or_404(Animal, pk=pk)
    form = ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        animal.image = request.FILES['image']
        animal.save()
        return redirect('animals:animal_detail', pk=pk)
    return render(request, 'animal_image.html', {'form':form, 'animal':animal})

animals/templates/animal.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{{ my_form.media }}

{% block content %}
  {% if owner %}<h2>Owner: {{ owner }}</h2>{% endif %}
  <h1>Animal Information</h1>
<div id="app">
  <form method="post" enctype="multipart/form-data"> {% csrf_token %}
    <div class="section-1">
      <div class="row">
        <div class="col-6">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.species|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          {{ form.sex|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.fixed|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.age|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.size|as_crispy_field }}
        </div>
      </div>
    </div>
    <div class="section-2">
      <div class="row">
      </div>
      <div class="row">
        <div class="col-6">
          {{ form.pcolor|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.scolor|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          {{ form.markings|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          {{ form.address|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.apartment|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {{ form.city|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.state|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.zip_code|as_crispy_field }}
        </div>
      </div>
    </div>
    <div class="section-3">
      <div class="row">
        <div class="col-6">
          {{ form.aggressive|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.behavior_notes|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          {{ form.owner|as_crispy_field }}
        </div>
      </div>
      <input type="submit" value="Save" class='btn btn-success btn-lg btn-block' id='submit-button'>
      <input class='btn btn-secondary btn-lg btn-block'  type=button value="Back" onClick="javascript:history.go(-1);">
      <br>
      <br>
    </div>

  </form>
</div>

<br>
<br>

{% endblock %}

animals/templates/animal_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>{{animal.name}}</h1>
  <hr>
  <div class="row">
    <div class="col-sm">
      <p><strong>Owner:</strong> {{animal.owner}} </p>
      <p><strong>Species:</strong> {{animal.species|title}} </p>
      <p><strong>Sex:</strong> {{animal.sex|title}} </p>
      <p><strong>Age:</strong> {{animal.age|title}} </p>
      <p><strong>Fixed:</strong> {{animal.fixed|yesno|title}} </p>
    </div>
    <div class="col-sm">
      <p><strong>Primary Color:</strong> {{animal.pcolor|title}} </p>
      <p><strong>Secondary Color:</strong> {{animal.scolor|title}} </p>
      <p><strong>Aggressive:</strong> {{animal.aggressive|yesno|title}} </p>
      <p><strong>Status:</strong> {{animal.status|title}} </p>
      <p><strong>Shelter Location:</strong> {% if animal.cage %}{{ animal.cage.room.building.shelter|title }}, {{ animal.cage.room.building|title }}, {{ animal.cage.room|title }}, {{ animal.cage|title }}{% else %}N/A{% endif %}</p>
    </div>
    <div class="col-sm">
        <img src="{% if animal.image %}{{ animal.image.url}}{% else %}{% static 'images/no_image_icon.png' %}{% endif %}" alt="{{ animal.name }}" style='max-width:400px;max-height:200px'>
          <br>
        <br>
    </div>
  </div>
  <div class="row">
    {% include "minimap.html" with object=animal %}
  </div>

  <a class='btn btn-info btn-lg btn-block' href="{% url 'animals:animal_edit' animal.pk %}">Update Animal</a>
  <a class='btn btn-info btn-lg btn-block' href="{% url 'animals:animal_image' animal.pk %}">{% if animal.image %}Update{% else %}Add{% endif %} Animal Image</a>
  <a class='btn btn-success btn-lg btn-block' href="{% url 'shelter:shelter_animal_shelter_select' animal.pk %}">{% if animal.cage %}Move{% else %}Shelter{% endif %} Animal</a>
  {% if animal.owner %}
  <a class='btn btn-secondary btn-lg btn-block' href="{% url 'people:owner_detail' animal.owner.pk %}">Back to Owner</a>
  {% endif %}
  {% if animal.servicerequest %}
  <a class='btn btn-secondary btn-lg btn-block' href="{% url 'people:owner_detail' animal.owner.pk %}">Back to Owner</a>
  {% endif %}
<br>
{% endblock %}

animals/templates/animal_image.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{{ my_form.media }}
{% block content %}

<style>
    #id_image {
        opacity: 0;
        height: 600px;
        width: 1100px;
        margin: auto;
    }

    #image-label {
         margin: auto;
         height: 50px;
    }

    #imageResult {
        width: 500px;
        height: 500px;
        margin: auto;
        outline-color: black;
        outline-style: dashed;
        background-image: url("{% if animal.image %}{{ animal.image.url}}{% else %}{% static 'images/no_image_icon.png' %}{% endif %}");
        background-repeat: no-repeat;
        background-position: center center;
    }

    

</style>
<h1>{{ animal.name }}</h1>
<br>
<form id="image-upload" method="post" enctype="multipart/form-data"> {% csrf_token %}
    <div id="image-label" value="change image" disabled>
       <input id="id_image" class="btn btn-primary btn-lg btn-block form-control border-0" type="file" name="image" accept="image/*" required="" onchange="readURL(this);">
    </div>
<br>
<br>
<div>
        <div class="image-area bg-white"><img id="imageResult" src="#" alt="" class="img-fluid rounded shadow-sm mx-auto d-block"></div>
</div>
    <br>
    <br>
<input type="submit" value="Save" class='btn btn-success btn-lg btn-block' id='submit-button'>
<input class='btn btn-secondary btn-lg btn-block' type=button value="Back" onClick="javascript:history.go(-1);">
</form> 
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imageResult')
                    .attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    $(function () {
        $('#upload').on('change', function () {
            readURL(input);
        });
    });
</script>
 {% endblock %}