hotline/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from hotline import views
from rest_framework.routers import DefaultRouter

from hotline.views import ServiceRequestViewSet


app_name = 'hotline'
router = DefaultRouter()
router.register(r'servicerequests', views.ServiceRequestViewSet)

urlpatterns = [
    path('', views.hotline_landing, name='hotline_landing'),
    path('api/', include(router.urls)),
    path('owner/new', views.hotline_new_owner, name='hotline_new_owner'),
    path('owner/<rep_pk>/new', views.hotline_new_owner, name = 'hotline_new_owner'),
    path('reporter/new', views.hotline_new_reporter, name = 'hotline_new_reporter'),
    path('request/list', views.service_request_list, name='service_request_list'),
    path('request/list/search/', views.service_request_search, name='service_request_search'),
    path('request/list/search/<query>', views.service_request_search, name='service_request_search'),
    path('request/list/<status>', views.service_request_list, name='service_request_list'),
    re_path(r'^request/(?P<owner_pk>\d+)(?:/(?P<rep_pk>\d+))?/new', views.service_request_new, name = 'service_request_new'),
    path('request/<int:service_request_pk>/', views.service_request_detail, name = 'service_request_detail'),
    path('request/<int:service_request_pk>/update', views.service_request_update, name = 'service_request_update'),
    path('request/<int:service_request_pk>/add/owner', views.service_request_add_owner, name = 'service_request_add_owner'),
    path('request/<service_request_pk>/animal/<species>/add', views.service_request_add_animal, name = "service_request_add_animal"),
]

people/urls.py
from django.contrib import admin
from django.urls import path

from people import views

app_name = 'people'

urlpatterns = [
    path('<int:pk>/delete', views.owner_delete, name='owner_delete'),
    path('<int:pk>/edit', views.owner, name='owner_edit'),
    path('<int:pk>/', views.owner_detail, name='owner_detail'),
]

urls.py
import views
import settings
from django.contrib import admin
from django.views.static import serve
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from knox import views as knox_views
from accounts.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('animals/', include('animals.urls')),
    path('evac/', include('evac.urls')),
    path('hotline/', include('hotline.urls')),
    path('intake/', include('intake.urls')),
    path('location/', include('location.urls')),
    path('people/', include('people.urls')),
    path('shelter/', include('shelter.urls')),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})]

hotline/models.py
from django.db import models
from location.models import Location
from people.models import Person

class ServiceRequest(Location):
    
    #keys
    owner = models.OneToOneField(Person, on_delete=models.SET_NULL, blank=True, null=True)
    reporter = models.ForeignKey(Person, on_delete=models.SET_NULL, blank=True, null=True, related_name='reported_servicerequest')

    #pre_field
    timestamp = models.DateTimeField(auto_now_add=True)
    directions = models.TextField(blank=True, null=True)
    verbal_permission = models.BooleanField(blank=True, null=True)
    key_provided = models.BooleanField(blank=True, null=True)
    accessible = models.BooleanField(blank=True, null=True)
    turn_around = models.BooleanField(blank=True, null=True)

    #post_field
    forced_entry = models.BooleanField(blank=True, null=True)
    outcome = models.TextField(blank=True, null=True)
    owner_notification_notes = models.TextField(blank=True, null=True)
    recovery_time = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
    owner_notification_tstamp = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        output = []
        output.append('Owner: %s' % self.owner or 'Unknown')
        if self.reporter:
            output.append('Reporter: %s' % self.reporter)
        output.append('Animal Count: %s' % self.animal_count)
        return ', '.join(output)

    @property
    def animal_count(self):
        return self.animal_set.all().count()
    
    @property
    def location_type(self):
        return 'service_request'

    class Meta:
        ordering = []

hotline/forms.py
from django import forms
from location.forms import LocationForm
from hotline.models import ServiceRequest
from people.models import Person


class ServiceRequestForm(LocationForm):

    directions = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))

    class Meta:
        model  = ServiceRequest
        fields = ['owner', 'directions', 'verbal_permission', 'outcome', 'key_provided', 'forced_entry', 'address']
        widgets = {'owner': forms.HiddenInput()}

class ServiceRequestSearchForm(forms.Form):

    search = forms.CharField(required=True)

hotline/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from .serializers import ServiceRequestSerializer
from animals.models import Animal
from animals.forms import AnimalForm
from hotline.models import ServiceRequest
from hotline.forms import ServiceRequestForm, ServiceRequestSearchForm
from people.models import Person
from people.forms import PersonForm
from rest_framework import viewsets
from django.core.files.storage import FileSystemStorage

# Create your views here.
def hotline_landing(request):
    return render(request, 'hotline_landing.html')

def hotline_new_owner(request, rep_pk=None):
    form = PersonForm(request.POST or None)
    if form.is_valid():
        owner = form.save()
        if rep_pk:
            return redirect('hotline:service_request_new', owner_pk=owner.pk, rep_pk=rep_pk)
        return redirect('hotline:service_request_new', owner_pk=owner.pk)
    return render(request, 'person.html', {'form':form, 'person_type':'Owner'})

def hotline_new_reporter(request):
    form = PersonForm(request.POST or None)
    if form.is_valid():
        reporter = form.save()
        return redirect('hotline:hotline_new_owner', rep_pk=reporter.pk)
    return render(request, 'person.html', {'form':form, 'person_type':'Reporter'})

def service_request_detail(request, service_request_pk):
    service_request = get_object_or_404(ServiceRequest, pk=service_request_pk)
    context = {'service_request':service_request}
    return render(request, 'service_request_details.html', context)

def service_request_new(request, owner_pk=None, rep_pk=None):
    reporter = Person.objects.get(pk=rep_pk) if rep_pk else None
    owner = Person.objects.get(pk=owner_pk) if owner_pk else None
    form = ServiceRequestForm(owner, request.POST or None)
    if form.is_valid():
        service_request = form.save()
        service_request.owner = owner
        service_request.reporter = reporter
        service_request.save()
        return redirect('hotline:service_request_detail', service_request_pk=service_request.pk)
    return render(request, 'service_request.html', {'form':form})

def service_request_update(request, service_request_pk):
    service_request = ServiceRequest.objects.get(pk=service_request_pk) if service_request_pk else None
    form = ServiceRequestForm(service_request, request.POST or None, instance=service_request)
    if form.is_valid():
        form.save()
        return redirect('hotline:service_request_detail', service_request_pk=service_request_pk)
    return render(request, 'service_request_edit.html', {'form':form})

def service_request_add_owner(request, service_request_pk):
    service_request = ServiceRequest.objects.get(pk=service_request_pk) if service_request_pk else None
    form = PersonForm(request.POST or None)
    if form.is_valid():
        owner = form.save()
        service_request.owner = owner
        service_request.save()
        return redirect('hotline:service_request_detail', service_request_pk=service_request_pk)
    return render(request, 'owner.html', {'form':form})

def service_request_add_animal(request, service_request_pk, species):
    service_request = ServiceRequest.objects.get(pk=service_request_pk)
    form = AnimalForm(species, service_request.owner, request.POST or None, initial={'owner':service_request.owner})
    if form.is_valid():
        animal = form.save()
        animal.request = service_request
        animal.save()
        return redirect('hotline:service_request_detail', service_request_pk=service_request_pk)
    return render(request, 'animal.html', {'form':form})

def service_request_search(request):
    service_requests, query = None, None
    if request.POST:
        query = request.POST['search']
        service_requests = ServiceRequest.objects.filter(Q(animal__name__icontains=query) |\
            Q(owner__first_name__icontains=query) | Q(owner__last_name__icontains=query) |\
            Q(reporter__first_name__icontains=query) | Q(reporter__last_name__icontains=query)|
            Q(owner__address__icontains=query) | Q(owner__city__icontains=query)).distinct()
    search_form = ServiceRequestSearchForm()
    search_form.fields['search'].initial = query
    data = {'form':search_form, 'service_requests':service_requests, 'query': query}
    return render(request, 'service_request_list.html', data)


def service_request_list(request, status='all'):
    if status == 'unresolved':
        service_requests = ServiceRequest.objects.filter(animal__status__in=['REPORTED', 'NOT FOUND']).distinct()
    elif status == 'resolved':
        service_requests = ServiceRequest.objects.exclude(animal__status__in=['REPORTED', 'NOT FOUND']).distinct()
    else:
        service_requests = ServiceRequest.objects.all().distinct()
    data = {'service_requests':service_requests, 'status': status}
    return render(request, 'service_request_list.html', data)

class ServiceRequestViewSet(viewsets.ModelViewSet):

    queryset = ServiceRequest.objects.all()
    serializer_class = ServiceRequestSerializer

hotline/templates/hotline_landing.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-warning btn-lg btn-block" href="{% url 'hotline:hotline_new_owner' %}">OWNER CALLING</a>
<a class="btn btn-warning btn-lg btn-block" href="{% url 'hotline:hotline_new_reporter' %}">NON-OWNER CALLING</a>
<a class="btn btn-warning btn-lg btn-block" href="{% url 'hotline:service_request_search' %}">SERVICE REQUESTS SEARCH</a>
<br>
<br>
<a class="btn btn-secondary btn-lg btn-block"  href="{% url 'home' %}">BACK</a>

{% endblock %}

hotline/templates/service_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <h1>Service Request Form</h1>
  <form action="" method="post">{% csrf_token %}
    <div class = 'section-1'>
      <div class = "row">
        <div class = "col-12">
          {{form.directions|as_crispy_field}}
        </div>
      </div>
      <div class = "row">
        <div class = "col-12">
          {{form.verbal_permission|as_crispy_field}}
          {{form.key_provided|as_crispy_field}}
        </div>
      </div>
    </div>
    <input type="submit" value="Save" class='btn btn-success btn-lg btn-block'>
    <input class='btn btn-secondary btn-lg btn-block'  type=button value="Cancel" onClick="javascript:history.go(-1);">
  </form>
{% endblock %}

hotline/templates/service_request_details.html
{% extends 'base.html' %}

{% block content %}

  {% if service_request.owner %}
  <h1>Owner: {{service_request.owner.first_name}} {{service_request.owner.last_name}}</h1>
  {% endif %}
  <br>
  {% if service_request.animal_set.all %}
  {% include "include/animal_table.html" with animals=service_request.animal_set.all %}
  {% endif %}
  <br>
  <a class='btn btn-success btn-lg btn-block' href="{% url 'hotline:service_request_add_animal' service_request.pk 'dog'%}">Add Dog</a>
  <a class='btn btn-success btn-lg btn-block'href="{% url 'hotline:service_request_add_animal' service_request.pk 'cat'%}">Add Cat</a>
  <a class='btn btn-success btn-lg btn-block' href="{% url 'hotline:service_request_add_animal' service_request.pk 'oth'%}">Add Other</a>
  <br>
  {% if service_request.owner %}
  <a class='btn btn-info btn-lg btn-block' href="{% url 'people:owner_edit' service_request.owner.pk %}">Edit Owner</a>
  {% else %}
  <a class='btn btn-success btn-lg btn-block' href="{% url 'hotline:service_request_add_owner' service_request.pk %}">Add Owner</a>
  {% endif %}
  <a class='btn btn-info btn-lg btn-block' href="{% url 'hotline:service_request_update' service_request.pk %}">Update Request</a>
  <input class='btn btn-secondary btn-lg btn-block' type=button value="Back" onClick="javascript:history.go(-1);">
  <br>
{% endblock %}

hotline/templates/service_request_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <h1>Evacuation Request</h1>
  <form action="" method="post">{% csrf_token %}
      <div class = "row">
        <div class = "col-12">
          {{form.outcome|as_crispy_field}}
        </div>
      </div>
      <div class = "row">
        <div class = "col-12">
          {{form.forced_entry|as_crispy_field}}
        </div>
      </div>
      <div>
        <div class = "row">
          <div class = "col-12">
            {{form.directions|as_crispy_field}}
          </div>
        </div>
      </div>
      <div class = "row">
        <div class = "col-6">
          {{form.verbal_permission|as_crispy_field}}
        </div>
        <div class = "col-6">
          {{form.key_provided|as_crispy_field}}
        </div>

      </div>
      <input type="submit" value="Save" class='btn btn-success btn-lg btn-block'>
      <input class='btn btn-secondary btn-lg btn-block'  type=button value="Cancel" onClick="javascript:history.go(-1);">
  </form>
{% endblock %}

hotline/templates/service_request_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <h1>{{ status|title }} Service Requests</h1>
  <br>
  <form action="" method="post">{% csrf_token %}
    {{form.search|as_crispy_field}}
    <input type="submit" value="Search" class='btn btn-success btn-lg btn-block'>
  </form>
  <br>
  {% if service_requests %}
    {% for service_request in service_requests %}
      <a class='btn btn-warning btn-lg btn-block' href="{% url 'people:owner_detail' service_request.owner.pk %}">{{service_request}}</a>
        {% include "include/animal_table.html" with animals=service_request.animal_set.all %}
    {% endfor %}
  {% else %}
    <a class='btn btn-secondary btn-lg btn-block disabled'>NO {{ status|upper }} SERVICE REQUESTS FOUND</a>
  {% endif %}
  <br>
  <br>
  <input class='btn btn-secondary btn-lg btn-block' type=button value="Back" onClick="javascript:history.go(-1);">
{% endblock content %}