animals/urls.py
from django.urls import path
from . import views

app_name = 'animals'

urlpatterns = [
    path('<int:pk>/', views.animal_detail, name='animal_detail'),
    path('<int:pk>/delete', views.animal_delete, name='animal_delete'),
    path('<int:pk>/edit', views.animal_edit, name="animal_edit"),
    path('<int:pk>/image-new', views.animal_image, name="animal_image"),
    #path('owner/<owner_pk>/animal', views.owner_animal_landing, name='owner_animal_landing'),
    path('', views.animal_list, name="animal_list"),
    path('<species>/new', views.new_animal, name='new_animal'),
    path('<species>/<owner_pk>/new', views.new_animal, name='new_animal'),
]

shelter/urls.py
from django.urls import path, include
from shelter import views

app_name = 'shelter'
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register(r'shelter', views.ShelterViewSet)
router.register(r'building', views.BuildingViewSet, basename='building')
router.register(r'room', views.RoomViewSet, basename='room')
# router.register('buildings/shelter/<int:shelter>', views.BuildingFilteredView)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.shelter_landing, name="shelter_landing"),
    path('list', views.shelter_list, name="shelter_list"),
    #Shelter Management URLs
    path('new', views.shelter, name='shelter'),
    path('<int:pk>/edit/', views.shelter, name='shelter'),
    path('<int:pk>/', views.shelter_detail, name='shelter_detail'),
    path('<int:shelter_pk>/building/', views.building, name='building'),
    path('<int:shelter_pk>/building/<int:pk>', views.building, name='building'),
    path('building/<int:pk>/', views.building_detail, name='building_detail'),
    path('building/<int:building_pk>/room', views.room, name='room'),
    path('building/<int:building_pk>/room/<int:pk>', views.room, name='room'),
    path('room/<int:pk>/', views.room_detail, name='room_detail'),
    path('<obj_type>/<int:pk>/delete', views.shelter_object_delete, name='shelter_object_delete'),

    # Animal Placement URLs
    path('<int:animal_pk>/shelter', views.shelter_animal_shelter_select, name='shelter_animal_shelter_select'),
    path('<int:animal_pk>/<int:shelter_pk>/buildings', views.shelter_animal_building_select, name='shelter_animal_building_select'),
    path('<int:animal_pk>/<int:building_pk>/rooms', views.shelter_animal_room_select, name='shelter_animal_room_select')

]

urls.py
import views
import settings
from django.contrib import admin
from django.views.static import serve
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from knox import views as knox_views
from accounts.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('animals/', include('animals.urls')),
    path('evac/', include('evac.urls')),
    path('hotline/', include('hotline.urls')),
    path('intake/', include('intake.urls')),
    path('location/', include('location.urls')),
    path('people/', include('people.urls')),
    path('shelter/', include('shelter.urls')),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})]

shelter/models.py
from django.db import models
from location.models import Location
# Create your models here.

class BaseShelterModel(models.Model):

    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=400, blank=True, null=True)

    def __str__(self):
        return self.name.upper()

    class Meta:
        abstract=True
        ordering = ['name',]

class Shelter(BaseShelterModel, Location):

    image = models.ImageField(upload_to='media/images/shelter', blank=True, null=True)

    @property
    def location_type(self):
        return 'shelter'
    

class Building(BaseShelterModel):

    shelter = models.ForeignKey(Shelter, on_delete=models.CASCADE)

    @property
    def parent(self):
        return self.shelter


class Room(BaseShelterModel):

    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    shelter = models.ForeignKey(Shelter, null=True, blank=True, on_delete=models.CASCADE)

    @property
    def parent(self):
        return self.building
   

shelter/forms.py
from django import forms

from shelter.models import Shelter, Building, Room

class ShelterForm(forms.ModelForm):

    class Meta:
        model = Shelter
        exclude = ['apartment']

class BuildingForm(forms.ModelForm):

    def __init__(self, shelter, *args, **kwargs):
        super(BuildingForm, self).__init__(*args, **kwargs)
        self.fields['shelter'].initial = shelter

    class Meta:
        model = Building
        fields = ['name', 'description', 'shelter']
        widgets = {'shelter': forms.HiddenInput()}

class RoomForm(forms.ModelForm):

    def __init__(self, building, *args, **kwargs):
        super(RoomForm, self).__init__(*args, **kwargs)
        self.fields['building'].initial = building

    class Meta:
        model = Room
        fields = ['name', 'description', 'building']
        widgets = {'building': forms.HiddenInput()}

shelter/views.py
from django.shortcuts import get_object_or_404, render, redirect

from animals.models import Animal
from shelter.models import Shelter, Building, Room
from shelter.forms import ShelterForm, BuildingForm, RoomForm
from rest_framework import viewsets, generics
from .serializer import ShelterSerializer, BuildingSerializer, RoomSerializer
from django_filters.rest_framework import DjangoFilterBackend
from django_filters import rest_framework as filters


OBJ_TYPE_DICT = {
    'building': (Building, 'shelter:shelter_detail'),
    'room': (Room, 'shelter:building_detail'),
}

# Create your views here.
def shelter_landing(request):
    return render(request, 'shelter_landing.html')

def shelter_list(request):
    shelter_list = Shelter.objects.all()
    return render(request, 'shelter_list.html', {'shelter_list':shelter_list})

def shelter_detail(request, pk):
    shelter = get_object_or_404(Shelter, pk=pk)
    return render(request, 'shelter_details.html', {'shelter':shelter})

def shelter(request, pk=None):
    instance = Shelter.objects.get(pk=pk) if pk else None
    form = ShelterForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('shelter:shelter_list')
    return render(request, 'shelter.html', {'form':form})

def building_detail(request, pk):
    building = get_object_or_404(Building, pk=pk)
    return render(request, 'building_details.html', {'building':building})

def building(request, shelter_pk, pk=None):
    instance = Building.objects.get(pk=pk) if pk else None
    shelter = Shelter.objects.get(pk=shelter_pk)
    form = BuildingForm(shelter, request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('shelter:shelter_detail', shelter_pk)
    return render(request, 'building.html', {'form':form})

def room_detail(request, pk):
    room = get_object_or_404(Room, pk=pk)
    return render(request, 'room_details.html', {'room':room})

def room(request, building_pk, pk=None):
    instance = Room.objects.get(pk=pk) if pk else None
    building = Building.objects.get(pk=building_pk)
    form = RoomForm(building, request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('shelter:building_detail', building_pk)
    return render(request, 'room.html', {'form':form})

def shelter_object_delete(request, obj_type, pk):
    obj = OBJ_TYPE_DICT[obj_type][0].objects.get(pk=pk)
    parent = obj.parent
    obj.delete()
    return redirect(OBJ_TYPE_DICT[obj_type][1], parent.pk)

def shelter_animal_shelter_select(request, animal_pk):
    animal = Animal.objects.get(pk=animal_pk)
    shelters = Shelter.objects.all()
    data = {'animal': animal, 'shelters':shelters}
    return render(request, 'shelter_select.html', data)

def shelter_animal_building_select(request, animal_pk, shelter_pk):
    animal = Animal.objects.get(pk=animal_pk)
    shelter = Shelter.objects.get(pk=shelter_pk)
    buildings = shelter.building_set.all()
    data = {'animal': animal, 'shelter':shelter, 'buildings':buildings}
    return render(request, 'building_select.html', data)

def shelter_animal_room_select(request, animal_pk, building_pk):
    animal = Animal.objects.get(pk=animal_pk)
    building = Building.objects.get(pk=building_pk)
    rooms = building.room_set.all()
    data = {'animal': animal, 'building': building, 'rooms':rooms}
    return render(request, 'room_select.html', data)

class ShelterViewSet(viewsets.ModelViewSet):
    queryset = Shelter.objects.all()
    serializer_class = ShelterSerializer


class BuildingViewSet(viewsets.ModelViewSet):
    queryset = Building.objects.all()
    serializer_class = BuildingSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_fields = ('shelter',)

class RoomViewSet(viewsets.ModelViewSet):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_fields = ('shelter', 'building',)

shelter/templates/building.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>ADD BUILDING TO {{ form.shelter.initial.name|upper }} SHELTER</h1>
<hr>
<div id="app">
  <form action="" method="post">{% csrf_token %}
      <div class="row">
        <div class="col-6">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.description|as_crispy_field }}
        </div>
      </div>
    {{ form.shelter|as_crispy_field }}
    <input type="submit" value="Save" class='btn btn-success btn-lg btn-block' id='submit-button'>
    <input class='btn btn-secondary btn-lg btn-block'  type=button value="Back" onClick="javascript:history.go(-1);">
  </form>
</div>
<br>
<br>
{% endblock %}mo

shelter/templates/building_details.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ building.name|upper }} BUILDING</h1>
<hr>
{% if building.room_set.exists %}
    {% for room in building.room_set.all %}
      <a class="btn btn-warning btn-lg btn-block" href="{% url 'shelter:room_detail' room.pk %}">{{ room }} ({{ room.counts }})</a>
    {% endfor %}
{% else %}
    <a class="btn btn-secondary btn-lg btn-block disabled">NO ROOMS CONFIGURED</a>
{% endif %}
<br>
<br>
<a class="btn btn-success btn-lg btn-block"  href="{% url 'shelter:room' building.pk %}">ADD ROOM</a>
<a class="btn btn-info btn-lg btn-block"  href="{% url 'shelter:building' building.shelter.pk building.pk %}">EDIT BUILDING</a>
<a class="btn btn-secondary btn-lg btn-block"  href="{% url 'shelter:shelter_detail' building.shelter.pk %}">BACK</a>
{% endblock %}

shelter/templates/building_select.html
{% extends 'base.html' %}

{% block content %}
  <h1>SELECT BUILDING FOR {{ animal.name|upper }}</h1>
  <hr>
  {% if buildings %}
    {% for building in buildings %}
      <a class="btn btn-warning btn-lg btn-block" href="{% url 'shelter:shelter_animal_room_select' animal.pk building.pk %}">{{ building }} ({{building.counts}})</a>
    {% endfor %}
  {% else %}
    <a class="btn btn-secondary btn-lg btn-block disabled">NO BUILDINGS CONFIGURED FOR {{ shelter }}</a>
  {% endif %}
  <br>
  <br>
  <a class="btn btn-secondary btn-lg btn-block"  href="{% url 'shelter:shelter_animal_shelter_select' animal.pk %}">BACK</a>
{% endblock %}

shelter/templates/room.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>ADD ROOM TO {{ form.building.initial.name|upper }} BUILDING</h1>
<hr>
<div id="app">
  <form action="" method="post">{% csrf_token %}
      <div class="row">
        <div class="col-6">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.description|as_crispy_field }}
        </div>
      </div>
    {{ form.building|as_crispy_field }}
    <input type="submit" value="Save" class='btn btn-success btn-lg btn-block' id='submit-button'>
    <input class='btn btn-secondary btn-lg btn-block'  type=button value="Back" onClick="javascript:history.go(-1);">
  </form>
</div>
<br>
<br>
{% endblock %}

shelter/templates/room_details.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ room.name|upper }} ROOM</h1>
<br>
<br>
<a class="btn btn-info btn-lg btn-block"  href="{% url 'shelter:room' room.building.pk room.pk %}">EDIT ROOM</a>
<a class="btn btn-secondary btn-lg btn-block"  href="{% url 'shelter:building_detail' room.building.pk %}">BACK</a>
{% endblock %}

shelter/templates/room_select.html
{% extends 'base.html' %}

{% block content %}
  <h1>SELECT ROOM FOR {{ animal.name|upper }}</h1>
  <hr>
  {% if rooms %}
    {% for room in rooms %}
      <a class="btn btn-warning btn-lg btn-block" {{ room }} ({{ room.counts }})</a>
    {% endfor %}
  {% else %}
    <a class="btn btn-secondary btn-lg btn-block disabled">NO ROOMS CONFIGURED FOR {{ building }}</a>
  {% endif %}
  <br>
  <br>
  <a class="btn btn-secondary btn-lg btn-block"  href="{% url 'shelter:shelter_animal_building_select' animal.pk building.shelter.pk %}">BACK</a>
{% endblock %}

shelter/templates/shelter.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>{% if form.instance %}{{ form.instance|upper }}{% else %}NEW{% endif %} SHELTER</h1>
<hr>
<div id="app">
  <form action="" method="post">{% csrf_token %}
    <div class='section-1'>
      <div class="row">
        <div class="col-6">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.description|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          {{ form.address|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {{ form.city|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.state|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.zip_code|as_crispy_field }}
        </div>
      </div>
    </div>
    <input type="submit" value="Save" class='btn btn-success btn-lg btn-block' id='submit-button'>
    <input class='btn btn-secondary btn-lg btn-block'  type=button value="Back" onClick="javascript:history.go(-1);">
  </form>
</div>
<br>
<br>
{% endblock %}

shelter/templates/shelter_details.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: center">{{ shelter.name|upper }} SHELTER</h1>
<hr>
<div class="row">
  {% include "minimap.html" with object=shelter %}
</div>
<br>
{% if shelter.building_set.exists %}
  {% for building in shelter.building_set.all %}
    <a class="btn btn-warning btn-lg btn-block" href="{% url 'shelter:building_detail' building.pk %}">{{ building }} ({{building.counts }})</a>
  {% endfor %}
{% else %}
    <a class="btn btn-secondary btn-lg btn-block disabled">NO BUILDINGS CONFIGURED</a>
{% endif %}
<br>
<br>
<a class="btn btn-success btn-lg btn-block"  href="{% url 'shelter:building' shelter.pk %}">ADD BUILDING</a>
<a class="btn btn-info btn-lg btn-block"  href="{% url 'shelter:shelter' shelter.pk %}">EDIT SHELTER</a>
<a class="btn btn-secondary btn-lg btn-block"  href="{% url 'shelter:shelter_list' %}">BACK</a>
{% endblock %}

shelter/templates/shelter_landing.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-warning btn-lg btn-block" href="{% url 'shelter:shelter_list' %}">SHELTER LIST</a>
<br>
<br>
<a class="btn btn-secondary btn-lg btn-block"  href="{% url 'home' %}">BACK</a>

{% endblock %}

shelter/templates/shelter_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>SHELTERS</h1>
  <hr>
  {% if shelter_list %}
    {% for shelter in shelter_list %}
      <a class="btn btn-warning btn-lg btn-block" href="{% url 'shelter:shelter_detail' shelter.pk %}">{{ shelter }} ({{ shelter.counts }})</a>
    {% endfor %}
  {% else %}
    <a class="btn btn-secondary btn-lg btn-block disabled">NO SHELTERS CONFIGURED</a>
  {% endif %}
  <br>
  <br>
  <a class="btn btn-success btn-lg btn-block"  href="{% url 'shelter:shelter' %}">ADD SHELTER</a>
  <a class="btn btn-secondary btn-lg btn-block"  href="{% url 'shelter:shelter_landing' %}">BACK</a>
{% endblock %}

shelter/templates/shelter_select.html
{% extends 'base.html' %}

{% block content %}
  <h1>SELECT SHELTER FOR {{ animal.name|upper }}</h1>
  <hr>
  {% if shelters %}
    {% for shelter in shelters %}
      <a class="btn btn-warning btn-lg btn-block" href="{% url 'shelter:shelter_animal_building_select' animal.pk shelter.pk %}">{{ shelter }} ({{ shelter.counts }})</a>
    {% endfor %}
  {% else %}
    <a class="btn btn-secondary btn-lg btn-block disabled">NO SHELTERS CONFIGURED</a>
  {% endif %}
  <br>
  <br>
  <a class="btn btn-secondary btn-lg btn-block"  href="{% url 'animals:animal_detail' animal.pk %}">BACK</a>
{% endblock %}