hotline/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from hotline import views
from rest_framework.routers import DefaultRouter

from hotline.views import ServiceRequestViewSet


app_name = 'hotline'
router = DefaultRouter()
router.register(r'servicerequests', views.ServiceRequestViewSet)

urlpatterns = [
    path('', views.hotline_landing, name='hotline_landing'),
    path('api/', include(router.urls)),
    path('owner/new', views.hotline_new_owner, name='hotline_new_owner'),
    path('owner/<rep_pk>/new', views.hotline_new_owner, name = 'hotline_new_owner'),
    path('reporter/new', views.hotline_new_reporter, name = 'hotline_new_reporter'),
    path('request/list', views.service_request_list, name='service_request_list'),
    path('request/list/search/', views.service_request_search, name='service_request_search'),
    path('request/list/search/<query>', views.service_request_search, name='service_request_search'),
    path('request/list/<status>', views.service_request_list, name='service_request_list'),
    re_path(r'^request/(?P<owner_pk>\d+)(?:/(?P<rep_pk>\d+))?/new', views.service_request_new, name = 'service_request_new'),
    path('request/<int:service_request_pk>/', views.service_request_detail, name = 'service_request_detail'),
    path('request/<int:service_request_pk>/update', views.service_request_update, name = 'service_request_update'),
    path('request/<int:service_request_pk>/add/owner', views.service_request_add_owner, name = 'service_request_add_owner'),
    path('request/<service_request_pk>/animal/<species>/add', views.service_request_add_animal, name = "service_request_add_animal"),
]

intake/urls.py
from django.contrib import admin
from django.urls import path

from intake import views

app_name = 'intake'

urlpatterns = [
    path('', views.intake_landing, name ='intake_landing'),
    path('owned/', views.intake_owned, name='intake_owned'),
    path('evacreq/select', views.select_evac_req, name='select_evac_req'),
    path('owned/<owner_pk>/<species>/new', views.intake_new_animal, name='intake_new_animal'),
]

people/urls.py
from django.contrib import admin
from django.urls import path

from people import views

app_name = 'people'

urlpatterns = [
    path('<int:pk>/delete', views.owner_delete, name='owner_delete'),
    path('<int:pk>/edit', views.owner, name='owner_edit'),
    path('<int:pk>/', views.owner_detail, name='owner_detail'),
]

urls.py
import views
import settings
from django.contrib import admin
from django.views.static import serve
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from knox import views as knox_views
from accounts.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('animals/', include('animals.urls')),
    path('evac/', include('evac.urls')),
    path('hotline/', include('hotline.urls')),
    path('intake/', include('intake.urls')),
    path('location/', include('location.urls')),
    path('people/', include('people.urls')),
    path('shelter/', include('shelter.urls')),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})]

people/models.py
from django.db import models
from location.models import Location
from form_utils import NAME_VALIDATOR, PHONE_VALIDATOR

class Person(Location):
    
    first_name = models.CharField(max_length=50, validators=[NAME_VALIDATOR])
    last_name = models.CharField(max_length=50, validators=[NAME_VALIDATOR])
    phone = models.CharField(max_length=50, blank=True, null=True, validators=[PHONE_VALIDATOR])
    best_contact = models.TextField(blank=True, null=True)
    drivers_license = models.CharField(max_length=50, blank=True, null=True)

    @property
    def location_type(self):
        return 'person'

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

people/forms.py
import re
from django import forms
from people.models import Person
from form_utils import NAME_VALIDATOR, PHONE_VALIDATOR, ZIP_VALIDATOR

class PersonForm(forms.ModelForm):

    best_contact = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))
    first_name = forms.CharField(required=False, validators=[NAME_VALIDATOR])
    last_name = forms.CharField(required=False, validators=[NAME_VALIDATOR])
    phone = forms.CharField(required=False, validators=[PHONE_VALIDATOR])
    city = forms.CharField(required=False, validators=[NAME_VALIDATOR])
    zip_code = forms.CharField(required=False, validators=[ZIP_VALIDATOR])

    class Meta:
        model = Person
        fields = [ 'first_name', 'last_name', \
            'phone', 'best_contact', 'drivers_license', \
            'address', 'apartment', 'city', \
            'state', 'zip_code', ]


class OwnerForm(forms.ModelForm):

    best_contact = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))
    first_name = forms.CharField(required=False, validators=[NAME_VALIDATOR])
    last_name = forms.CharField(required=False, validators=[NAME_VALIDATOR])
    phone = forms.CharField(required=False, validators=[PHONE_VALIDATOR])
    city = forms.CharField(required=False, validators=[NAME_VALIDATOR])
    zip_code = forms.CharField(required=False, validators=[ZIP_VALIDATOR])

    class Meta:
        model = Person
        fields = [ 'first_name', 'last_name', \
            'phone', 'best_contact', 'drivers_license', \
            'address', 'apartment', 'city', \
            'state', 'zip_code', ]

people/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.db.models import Q
from rest_framework import permissions, viewsets

from animals.models import Animal
from people.models import Person
from hotline.models import ServiceRequest
from people.forms import PersonForm

def owner(request, pk=None):
    owner = get_object_or_404(Person, pk=pk) if pk else None
    form = PersonForm(request.POST or None, instance=owner)
    if form.is_valid():
        form.save()
        return redirect('people:owner_detail', owner.pk)
    return render(request, 'person.html', {'form':form, 'person_type': 'Owner'})

def owner_delete(request, pk):
    owner = get_object_or_404(Person, pk=pk)
    if request.POST:
        owner.delete()
        return render(request, 'owner_delete_success.html')
    context = {
    'owner':owner,
    }
    return render(request, "owner_delete.html", context)

def owner_detail(request, pk):
    owner = get_object_or_404(Person, pk=pk)
    return render(request, 'owner_detail.html', {'owner':owner})

people/templates/owner_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Owner</h1>
<form action="" method="post">{% csrf_token %}
  <p>Delete "{{owner.first_name}} {{owner.last_name}}" From Database?</p>
  <input class="btn btn-danger btn-lg btn-block" type="submit" name="" value="Confirm">
</form>
<br>
<br>
<a class="btn btn-secondary btn-lg btn-block" href="{% url 'people:owner_list' %}">Cancel</a>



{% endblock %}

people/templates/owner_delete_success.html
{% extends 'base.html' %}

{% block content %}
<h1>Owner Successfully Removed From Database</h1>

<a class="btn btn-primary btn-lg btn-block" href="{% url 'people:owner_list' %}">Back To Owner List</a>

{% endblock %}

people/templates/owner_detail.html
{% extends 'base.html' %}

{% block content %}

  <h1>{{owner.first_name}} {{owner.last_name}}</h1>
  <hr>
  <div class="row">
    <div class="col-sm">
      <p><strong>Phone:</strong>
        {% if owner.home_phone %}{{ owner.home_phone }} (H) {% endif %}
        {% if owner.work_phone %}{{ owner.work_phone}} (W) {% endif %}
        {% if owner.cell_phone %}{{ owner.cell_phone}} (C) {% endif %}
      </p>
      <p><strong>Drivers License:</strong> {{owner.drivers_license}} </p>
      <p><strong>Best Contact:</strong> {{owner.best_contact}} </p>
      <p><strong>Address:</strong> {{ owner.location_output }}</p>
    </div>
    <div class="col-sm">
    {% if owner.servicerequest %}
        <p><strong>Time of Request:</strong> {{owner.servicerequest.timestamp}}</p>
        <p><strong>Verbal Permission:</strong> {{owner.servicerequest.verbal_permission}}</p>
        <p><strong>Request Location:</strong> {{ owner.servicerequest.location_output }}</p>
    {% endif %}
    </div>
  </div>
  {% if owner.animal_set.all %}
  <h1>ANIMALS</h1>
      {% include "include/animal_table.html" with animals=owner.animal_set.all %}
  {% endif %}
  <br>
  <br>
  <a class='btn btn-success btn-lg btn-block' href="{% url 'intake:intake_new_animal' owner.pk 'dog'%}">Add Dog</a>
  <a class='btn btn-success btn-lg btn-block'href="{% url 'intake:intake_new_animal' owner.pk 'cat'%}">Add Cat</a>
  <a class='btn btn-success btn-lg btn-block' href="{% url 'intake:intake_new_animal' owner.pk 'oth'%}">Add Other</a>
  <a class='btn btn-info btn-lg btn-block' href="{% url 'people:owner_edit' owner.pk %}">Update Owner</a>
  {% if owner.servicerequest %}
  <a class='btn btn-info btn-lg btn-block' href="{% url 'hotline:service_request_update' owner.servicerequest.pk %}">Update Request</a>
  {% endif %}
  <input class='btn btn-secondary btn-lg btn-block'  type=button value="Back" onClick="javascript:history.go(-1);">
  <br>
{% endblock %}

people/templates/person.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>{{ person_type }} Information</h1>
<div id="app">
  <form action="" method="post">{% csrf_token %}
    <div class='section-1'>
      <div class="row">
        <div class="col-12">
          {{ form.first_name|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          {{ form.last_name|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {{ form.phone|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.best_contact|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.drivers_license|as_crispy_field }}
        </div>
      </div>
    </div>
    <div class='section-2'>
      <div class="row">
        <div class="col-6">
          {{ form.address|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.apartment|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {{ form.city|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.state|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.zip_code|as_crispy_field }}
        </div>
      </div>
      <input type="submit" value="Save" class='btn btn-success btn-lg btn-block' id='submit-button'>
      <input class='btn btn-secondary btn-lg btn-block'  type=button value="Cancel" onClick="javascript:history.go(-1);">
      <br>
      <br>
    </div>
    <div>
    </div>
  </form>
</div>
<br>
<br>

{% endblock %}

people/templates/team_member.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Team Member</h1>
<form action="" method="post">{% csrf_token %}
    <div class="row">
        <div class="col-6">
          {{ form.first_name|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.last_name|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
          {{ form.cell_phone|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.agency_id|as_crispy_field }}
        </div>
    </div>
<input type="submit" value="Save" class='btn btn-success' id='submit-button'>
<a class='btn btn-secondary' href="{% url 'evac:evac_landing' %}">Cancel</a>
</form>

{% endblock content %}